# Generated by Django 3.0.5 on 2020-04-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_auto_20200420_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture_path',
            field=models.CharField(default='https://pingwinosblogbucket.s3.eu-west-1.amazonaws.com/test.jpg', max_length=248),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vestibulum risus purus, at maximus orci scelerisque et. Sed lobortis rutrum ex nec cursus. Integer quam est, semper ut nibh at, bibendum tempus magna. Quisque scelerisque ante et erat ornare varius. Vivamus ut nisi vulputate, laoreet magna quis, fringilla enim. Donec leo est, vestibulum vitae scelerisque vel, tristique eget lacus. Sed pellentesque elementum tortor, vulputate suscipit velit fermentum ut. Curabitur blandit cursus dolor, in sodales quam tincidunt sit amet. In vitae odio in mi tincidunt mattis. Donec semper libero ligula, et bibendum nisl imperdiet sed. Proin commodo est turpis, vel volutpat magna congue eleifend. In maximus ex sed purus semper, et sagittis ex lobortis. Nulla vitae scelerisque risus. Aenean sed mollis dui. Proin ut libero porttitor, cursus est sit amet, feugiat metus. Nunc semper arcu vel viverra aliquam. Pellentesque at magna ipsum. Proin nec viverra sem. Morbi interdum, augue non ultricies sodales, diam massa ultricies libero, vitae ultricies augue orci quis lectus. Vivamus dictum arcu non malesuada vehicula. In non tincidunt nulla, nec rutrum est. Cras eleifend ultrices nisl, sed vulputate nibh bibendum vel. Aliquam et purus rutrum, tempus ligula sit amet, tincidunt nibh. Nulla vel volutpat odio, et consectetur nibh. Vestibulum mattis magna et lobortis consectetur. Donec eget arcu aliquet, dictum metus non, rhoncus magna. Maecenas rhoncus auctor pulvinar. Praesent sit amet metus erat. Nunc eget est id lacus finibus tempus a non nulla. Ut fringilla, urna vel lacinia imperdiet, dui tortor ultricies ligula, et aliquameros odio sed lacus. Vestibulum id varius justo, vitae pretium leo. Integer vel convallis metus. Fusce dapibus dui vel risus suscipit, sed ultricies ligula fermentum. Morbi quis convallis nunc. Donec placerat nisi metus, ac imperdiet felis commodo in. Suspendisse in mauris augue. Ut vestibulum cursus quam, sit amet condimentum dolor. Suspendisse elementum semper pellentesque. Duis accumsan ante metus, et volutpat mauris tincidunt vitae. Sed dapibus commodo felis a finibus. Sed eget tortor sit amet neque dapibus imperdiet. Donec porta elementum massa, sed euismod tellus hendrerit eget. Pellentesque sagittis sollicitudin massa sit amet feugiat. Donec sed molestie mi. Etiam ultricies scelerisque nulla id tempus. Vestibulum eu dui at libero scelerisque tempor scelerisque ut mauris. Integer posuere, justo eu sollicitudin laoreet, nulla nunc mollis neque, vitae dapibus nisl ipsum a orci. Fusce commodo lectus augue, ac viverra dolor bibendum in. In dignissim varius dolor, a ornare nulla aliquam in. Mauris finibus elit ac metus aliquet sodales. In consequat eget nibh sit amet mattis. Curabitur et gravida lectus, commodo hendrerit nisl. Donec massa diam, sodales at ultrices sit amet, mollis a urna. Phasellus vel massa sem. Praesent vulputate erat ac consectetur placerat. Aliquam erat volutpat. Quisque quis odio id velit semper viverra et quis nibh. Curabitur semper elit a leo vulputate molestie. Vestibulum lobortis purus id finibus aliquam. Suspendisse orci sem, consectetur nec ligula vel, finibus egestas augue.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Test Title', max_length=124),
        ),
    ]
