# Generated by Django 3.0.5 on 2020-04-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0003_auto_20200422_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_picture',
            field=models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to=''),
        ),
    ]
