# Generated by Django 3.0.5 on 2020-04-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0004_post_upload_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture_path',
            field=models.CharField(default='https://pingwinosblogbucket.s3.eu-west-1.amazonaws.com', max_length=248),
        ),
    ]
