# Generated by Django 3.0.5 on 2020-04-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0005_auto_20200422_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture_path',
            field=models.CharField(default='settings.MEDIA_ROOT/', max_length=248),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
