# Generated by Django 3.0.5 on 2020-04-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0006_auto_20200422_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture_path',
            field=models.CharField(default='settings.MEDIA_ROOT/14ed3a5b-e7a7-4ace-bdc5-d79c4c9c93fb', max_length=248),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_picture',
            field=models.ImageField(upload_to='settings.MEDIA_ROOT/14ed3a5b-e7a7-4ace-bdc5-d79c4c9c93fb'),
        ),
    ]
