# Generated by Django 3.0.5 on 2020-04-22 21:18

from django.db import migrations, models
import posts_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0007_auto_20200422_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture_path',
            field=models.CharField(default='settings.MEDIA_ROOT/50f1ab0f-5336-4687-ae85-ba405755e609', max_length=248),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_picture',
            field=models.ImageField(upload_to=posts_app.models.update_filename),
        ),
    ]
