# Generated by Django 3.0.5 on 2020-04-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0008_auto_20200422_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upload_picture',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='post',
            name='picture_path',
        ),
    ]
