# Generated by Django 3.0.5 on 2020-04-30 18:58

from django.db import migrations, models
import posts_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags_app', '0002_auto_20200420_0058'),
        ('posts_app', '0009_auto_20200422_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='hash_tags',
            field=models.ManyToManyField(blank=True, to='hashtags_app.HashTag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default=None, upload_to=posts_app.models.update_filename),
        ),
    ]
