# Generated by Django 3.0.5 on 2020-04-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
